name: Prod Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    name: Test and Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.16.0"

      - name: Install Dependencies
        run: npm install

      #- name: Run Tests
      #  run: yarn test

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./build

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ./build

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump Version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}